name: Build and Deploy Website

on:
  push:
    branches:
      - master

# for OIDC
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Install Project Dependencies
        run: npm ci
      
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@4.24.0
      
      - name: Build
        run: gatsby build
      
      - name: Verify build
        run: ls -la public

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::134440022670:role/github_gatsby_myprofile_cicd
          aws-region: us-east-1

      - name: Upload to S3
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 sync public s3://$S3_BUCKET --delete --exact-timestamps

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::134440022670:role/github_gatsby_myprofile_cicd
          aws-region: us-east-1

      - name: Invalidate CloudFront cache
        env:
          DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
